version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default     

    steps:
      - checkout
      - run: Install-Module Invoke-MsBuild -Force
      - run:
          name: "Create output directory"
          command: mkdir output
      - run: dotnet restore
      - run:
          name: "Build and pack to win-x64"
          command: |
            $env:MSBuildSDKsPath = "C:\Program Files\dotnet\sdk\$(dotnet --version)\Sdks"
            Invoke-MsBuild -Path .\CovidInfoPH.sln -MsBuildParameters "-property:Configuration=Release -p:RuntimeIdentifier=win-x64 -p:OutputPath=win-x64/"
            [xml]$cn = Get-Content CovidInfoPH\CovidInfoPH.csproj
            if (!([string]::IsNullOrWhiteSpace($cn.Project.PropertyGroup.VersionSuffix))) { $outputPath = "output/CovidInfoPH.$(([string]$cn.Project.PropertyGroup.VersionPrefix).Trim())-$(([string]$cn.Project.PropertyGroup.VersionSuffix).Trim()).win-x64.zip"}
            else { $outputPath = "output/CovidInfoPH.$(([string]$cn.Project.PropertyGroup.VersionPrefix).Trim()).win-x64.zip" }
            Compress-Archive -Path CovidInfoPH\win-x64\ -DestinationPath $outputPath
      - store_artifacts:
          path: output
      - persist_to_workspace:
          root:  ./
          paths: output

  release-on-github:
    docker:
      - image: cibuilds/github:0.13

    steps:
      - attach_workspace:
          at: .
      - run: ls
      - run:
          name: "Release to GitHub"
          command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 $CIRCLE_TAG output/
  
  pre-release-on-github:
    docker:
      - image: cibuilds/github:0.13

    steps:
      - attach_workspace:
          at: .
      - run: ls
      - run:
          name: "Release to GitHub"
          command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 -prerelease $CIRCLE_TAG output/

workflows:
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /v(\d|[1-9]\d*)\.(\d|[1-9]\d*)\.(\d|[1-9]\d*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/
      - pre-release-on-github:
          requires:
            - build
          filters:
            tags:
              only: /v(\d|[1-9]\d*)\.(\d|[1-9]\d*)\.(\d|[1-9]\d*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/
            branches:
              ignore: /.*/
      - release-on-github:
          requires:
            - build
          filters:
            tags:
              only: /v(\d|[1-9]\d*)\.(\d|[1-9]\d*)\.(\d|[1-9]\d*)(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/
            branches:
              ignore: /.*/